apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
    - name: my-app-pod
      image: nginx
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
  initContainers:
    - name: init-page-setup
      image: busybox
      command: ["sh", "-c", "echo '<h1>Welcome to LbisTech</h1>' > /usr/share/nginx/html/index.html"]
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
  volumes:
    - name: shared-data
      emptyDir: {}
