apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
spec:
  selector:
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
  type: NodePort
