---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: mysql-secret
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: {{ .Values.aws.secretName }}
        property: dbname
    - secretKey: MYSQL_USER
      remoteRef:
        key: {{ .Values.aws.secretName }}
        property: username
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: {{ .Values.aws.secretName }}
        property: password
