---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
spec:
  type: {{ .Values.service.mysql.type }}
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: {{ .Values.service.mysql.port }}
    targetPort: 3306
