---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: default
spec:
  type: {{ .Values.service.wordpress.type }}
  selector:
    app: wordpress
  ports:
  - protocol: TCP
    port: {{ .Values.service.wordpress.port }}
    targetPort: 80
