---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wordpress-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: wordpress-secret
    creationPolicy: Owner
  data:
    - secretKey: WORDPRESS_DB_USER
      remoteRef:
        key: {{ .Values.aws.secretName }}
        property: username
    - secretKey: WORDPRESS_DB_PASSWORD
      remoteRef:
        key: {{ .Values.aws.secretName }}
        property: password
    - secretKey: WORDPRESS_DB_NAME
      remoteRef:
        key: {{ .Values.aws.secretName }}
        property: dbname
    - secretKey: WORDPRESS_DB_HOST
      remoteRef:
        key: {{ .Values.aws.secretName }}
        property: host
