# *** No need for this because we have created the service in php manifest section ***

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: nginx-config
#   namespace: two-tier-app
# data:
#   default.conf: |
#     server {
#         listen 80;
#         server_name _;

#         location / {
#             proxy_pass http://php-service:80;
#             proxy_set_header Host $host;
#             proxy_set_header X-Real-IP $remote_addr;
#             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#             proxy_set_header X-Forwarded-Proto $scheme;
#         }
#     }