apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
    - name: my-app-pod
      image: nginx
      volumeMounts:
        - name: log-volume
          mountPath: /var/log/nginx
    - name: logging-sidecar-container
      image: fluentd
      volumeMounts:
        - name: log-volume
          mountPath: /var/log/nginx
  volumes:
    - name: log-volume
      emptyDir: {}
