apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  volumes:
    - name: storage-volume
      persistentVolumeClaim:
        claimName: my-pvc
  containers:
    - name: busybox
      image: busybox
      command: [ "sh", "-c", "echo 'Hello Kubernetes Storage' > /mnt/data/message.txt && sleep 3600" ]
      volumeMounts:
        - mountPath: "/mnt/data"
          name: storage-volume
