version: '3'
services:
  web:
    container_name: nginx_01
    image: nginx:alpine
    ports:
      - 80:80
    networks:
      - my_network_app
  db:
    container_name: mysql_01
    image: mysql
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - "my_database_vol:/var/lib/mysql"
    networks:
      - my_network_app

volumes:
  my_database_vol:

networks:
  my_network_app:
