apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: two-tier-app
spec:
  selector:
    app: mysql
  type: ClusterIP  # Internal access only
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306