apiVersion: v1
kind: Pod
metadata:
  name: web-init
spec:
  initContainers:
    - name: init-myservice
      image: busybox
      command: ['sh', '-c', 'echo "Initializing..." && sleep 15']
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
