apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ=  # Base64 encoded command "echo -n "yourpassword" | base64"
  mysql-password: d29yZHByZXNz  # Base64 for "wordpresspass"
