apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-ebs
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0455c03b5ec8408cd
    fsType: ext4
