apiVersion: v1
kind: Pod
metadata:
  name: sidecar-demo
spec:
  volumes:
    - name: shared-logs
      emptyDir: {}
  containers:
    - name: main-app
      image: busybox
      command: ['sh', '-c', 'while true; do echo "$(date) - app running" >> /var/log/app.log; sleep 5; done']
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log
    - name: log-agent
      image: busybox
      command: ['sh', '-c', 'tail -f /var/log/app.log']
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log
