version: '3.1'

services:
  web:
    container_name: webserver01
    image: nginx:alpine
    ports:
      - 80:80
    
  db:
    container_name: mysql-db
    image: mysql
    ports:
      - 3306:3306
    env_file:
      - env_file.txt